name: Build macOS Python App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build on macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || true

    - name: Build app with PyInstaller
      run: |
        pyinstaller main.py --noconfirm --onefile --windowed --name=MyPythonApp

    - name: Show build output
      run: ls -lh dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-python-app
        path: dist/MyPythonApp
